config/routes.rb
Rails.application.routes.draw do
  root 'workspace#index'
  get '/name', to: 'workspace#name'
  get '/colors', to: 'workspace#colors'
  get '/visibility', to: 'workspace#visibility'
  get '/headings', to: 'workspace#headings'
  get '/delete_all', to: 'workspace#delete_all'
  get '/clicks', to: 'workspace#clicks'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/workspace_controller.rb
class WorkspaceController < ApplicationController
  def index
    render :index
  end

  def name
    render :name
  end

  def colors
    render :colors
  end

  def visibility
    render :visibility
  end

  def headings
    render :headings
  end

  def delete_all
    render :delete_all
  end

  def clicks
    render :clicks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workspace_helper.rb
module WorkspaceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JqueryWorkshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/workspace/clicks.html.erb
<h4><%= link_to "Back to List of Challenges", root_path %></h4>

<div class="challenges">
    <button id="click-me">Click Me!</button>
    <h4 id="nice-click">Nice Click!</h4>
</div>

app/views/workspace/colors.html.erb
<h4><%= link_to "Back to List of Challenges", root_path %></h4>

<div class="challenges">
  <h2 id='make-my-background-yellow'>Make My Background Yellow!</h2>
  <h2 id='make-my-background-purple'>Make My Background Purple!</h2>
  <h2 id='make-me-red'>Make Me Red!</h2>
  <h2 id='make-me-blue'>Make Me Blue!</h2>
  <h2 id='make-my-border-black'>Make My Border Black!</h2>
  <h2 id='make-my-border-orange'>Make My Border Orange!</h2>
</div>

app/views/workspace/delete_all.html.erb
<h4><%= link_to "Back to List of Challenges", root_path %></h4>

<div class="challenges">
  <h4>Delete Me!</h4>
  <h4>Delete Me Too!</h4>
  <h4>Delete Me As Well!</h4>
  <h4>Delete Me! Delete Me!</h4>
  <h4>Delete Me Now!</h4>
  <h4>Delete Me! No one would even care :-(</h4>
</div>

app/views/workspace/headings.html.erb
<h4><%= link_to "Back to List of Challenges", root_path %></h4>

<div class="challenges">
  <h2 id='add-subheading'>Add A Subheading Below Me</h2>
  <h3 id='add-heading'>Add A Heading Above Me</h3>
</div>

app/views/workspace/index.html.erb
<h1>jQuery Workshop</h1>
<h2>Instructions:</h2>

<p>
  Below you will find links to several challenges that will help you expand your basic knowledge of jQuery.
  There are often many ways to accomplish the same task, sometimes with slightly different results.
  If you finish a challenge quickly, try making the same thing happen with a different jQuery method!
</p>

<p>The <a href="https://api.jquery.com/category/attributes/">jQuery documentation</a>)
  will be your best resource for learning about different methods to accomplish the challenges.
  <br>
  <a href="http://www.w3schools.com/jquery/">W3 Schools</a> also has pretty good documentation of jQuery methods with easy-to-understand examples.</p>

<p>However, the documentation can be hard to understand for beginners,
  so if you get stuck, try typing your question into <a href="http://google.com">Google</a>.
  <br>
  For example, you could write "How do I change an element's color with jQuery?"
  <br>
  You may find a good response on a programming forum like <a href="http://stackoverflow.com/">Stack Overflow</a>,
  or a blog post that explains the topic you are trying to understand.
</p>

<h3>Good Luck!</h3>

<h2>List of jQuery Challenges:</h2>

<%= link_to "Name", name_path %>
<br>
<%= link_to "Colors", colors_path %>
<br>
<%= link_to "Visibility", visibility_path %>
<br>
<%= link_to "Headings", headings_path %>
<br>
<%= link_to "Delete All", delete_all_path %>
<br>
<%= link_to "Clicks", clicks_path %>
<br>

app/views/workspace/name.html.erb
<h4><%= link_to "Back to List of Challenges", root_path %></h4>

<div class="challenges">
  <h4 id='my-name'>WRITE YOUR NAME HERE<h4>
</div>

app/views/workspace/visibility.html.erb
<h4><%= link_to "Back to List of Challenges", root_path %></h4>

<div class="challenges">
  <h2 id='make-me-disappear'>Make Me Disappear!</h2>
  <h2><span id='make-me-appear'>Make Me Appear!</span>
    &larr; there is text here, make it appear!</h2>
</div>